### ISSUE TITLE
Please update / remove from pypi

### ISSUE THREAD

**Issue by dreua** [bittorrent/bencode#3]
*Originally sent to thomas@bittorrent.com but since his mail does not exist anymore posting this here.*

Hello Thomas,

the bencode Package you distribute via pypi does not work with recent Python (3.7.7). I get the error: 
```
$ python3
Python 3.7.7 (default, Mar 13 2020, 10:23:39)
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bencode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/da/.local/lib/python3.7/site-packages/bencode/__init__.py", line 13, in <module>
    from BTL import BTFailure
ModuleNotFoundError: No module named 'BTL' 
```

Please consider updating or removing this module since it is wasting peoples' time. There are working alternatives like bencode.py so removal would be a viable option.

Best regards

**Comment by alx-xlx** [comment]
What are it's alternatives ?

**Comment by dreua** [comment]
I think I ended up using, bencode-open:
https://github.com/imachug/bencode-open
https://pypi.org/project/bencode-open/

**Comment by magbone** [comment]
You can try this [repo](https://github.com/magbone/bencode), I update the python version to 3.9(maybe 3.x also can work). Note that  the argument type of ```bdecode``` function is ```str```,  you should decode with ```latin_1``` encoding first.
